### ISSUE TITLE
helix-logging creates empty requests table

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-logging#116]
**Description** 
an empty requests table is created for every dataset in Bigquery

**To Reproduce**
1. Go to console of bigquery
2. select proper helix project. 
3. choose any dataset
4. view tables and observe each dataset has an empty requests table

**Expected behavior**
redundant table shouldn't exist!

**Screenshots**
*
![Screen Shot 2019-10-10 at 11 45 01 AM](https://user-images.githubusercontent.com/12217245/66597249-72106200-eb53-11e9-93a5-cdeabb736c34.png)

**Comment by trieloff** [comment]
I think this is not an issue, but an artifact of the date-based sharding in Google Bigquery.
